source 'https://rubygems.org'

gem 'sinatra'
gem 'rake'
gem 'rails'
gem 'sshkit'
gem 'capistrano', '~> 3.14'
gem 'capistrano-rails', '~> 1.6'
gem 'capistrano-bundler', '~> 2.0'
gem 'capistrano-rbenv', '~> 2.1'
